apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-backend
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  defaultBackend:
    service:
      name: app3
      port:
        number: 80
