Vagrant.configure("2") do |config|
  config.vm.box = "debian/trixie64"

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provider "libvirt" do |lv|
    lv.cpus = 2
    lv.memory = 2048
  end

  # ===== Server VM =====
  config.vm.define "smilosavS" do |s|
    s.vm.hostname = "smilosavS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provision "shell", path: "scripts/server.sh"
  end
end