Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.synced_folder ".", "/vagrant", type:"virtualbox"

    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = 2048
        vb.gui = false
    end

    # ===== Server VM =====
    config.vm.define "smilosavS" do |s|
        s.vm.hostname = "smilosavS"
        s.vm.network "private_network", ip: "192.168.56.110"
        s.vm.provision "shell", path: "scripts/server.sh"
    end
end
