Vagrant.configure("2") do |config|
    config.vm.box = "debian/trixie64"
    config.vm.synced_folder ".", "/vagrant", type:"rsync"

    k3s_token = "iotClusterToken"

    config.vm.provider "libvirt" do |lv|
        lv.cpus = 1
        lv.memory = 1024
    end

    # ===== Server VM =====
    config.vm.define "smilosavS" do |s|
        s.vm.hostname = "smilosavS"
        s.vm.network "private_network", ip: "192.168.56.110"
        s.vm.provision "shell", path: "scripts/server.sh", 
              env: {"K3S_TOKEN" => k3s_token}
    end

    # ===== Worker VM =====
    config.vm.define "smilosavSW" do |w|
        w.vm.hostname = "smilosavSW"
        w.vm.network "private_network", ip: "192.168.56.111"
        w.vm.provision "shell", path: "scripts/agent.sh",
              env: {"K3S_TOKEN" => k3s_token}
    end
end
