Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"

    #default provider settings
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 1024
        vb.gui = false
    end

    # ===== Server VM =====
    config.vm.define "smilosavS" do |s|
        s.vm.hostname = "smilosavS"
        #host-only (private) network with the exact required IP
        s.vm.network "private_network", ip: "192.168.56.110"
    end

    # ===== Worker VM =====
    config.vm.define "smilosavSW" do |w|
        w.vm.hostname = "smilosavSW"
        w.vm.network "private_network", ip: "192.168.56.111"
    end
end
