Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.synced_folder ".", "/vagrant", type:"virtualbox"

    #default provider settings
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 1024
        vb.gui = false
    end

    # ===== Server VM =====
    config.vm.define "smilosavS" do |s|
        s.vm.hostname = "smilosavS"
        #host-only (private) network with the exact required IP
        s.vm.network "private_network", ip: "192.168.56.110"
        s.vm.provision "shell", path: "scripts/server.sh"
    end

    # ===== Worker VM =====
    config.vm.define "smilosavSW" do |w|
        w.vm.hostname = "smilosavSW"
        w.vm.network "private_network", ip: "192.168.56.111"
        w.vm.provision "shell", path: "scripts/agent.sh"
    end
end
